  gitalk: true
  gitalk_clientID: '9f420628592c46d047bb'
  gitalk_Secret: 'c77244cce6a00e0be287c748b574f4b6012a09ec'
  gitalk_repo: â€™nick-job.github.io'
  gitalk_owner: 'nick-job'
  gitalk_admin: 'nick-job'
  distractionFreeMode: true
